-- Generated by Omagen. Window style: border=spin border_size=0 shape=rounded spacing=native depth=shadow inactive=blur.
local active_border_color = { colors = { "rgb(5f73c9)", "rgb(5e79bd)", "rgb(baa8ce)", "rgb(5f73c9)" }, angle = 0 }
local inactive_border_color = "rgb(7c7883)"

hl.config({
  general = {
    col = { active_border = active_border_color, inactive_border = inactive_border_color },
  },
  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },
  decoration = {
    rounding = 8, rounding_power = 3,
    shadow = { enabled = true, render_power = 3, range = 18, color = "rgba(091021e6)", color_inactive = "rgba(091021b8)" },
    inactive_opacity = 0.58, dim_inactive = true, dim_strength = 0.62,
    blur = { enabled = true, size = 16, passes = 3, ignore_opacity = false, new_optimizations = true },
  },
})

-- Keep the accent gradient moving around the focused pane.
hl.animation({ leaf = "borderangle", enabled = true, speed = 36, bezier = "linear", style = "loop" })
