"""The Plymouth script for the Hikari 99 boot screen, one complete scene per
screen. Imported by render.py once the drawings are made; see write_script().

Plymouth puts every screen on one canvas, centred on the largest, so a
smaller screen normally shows the middle of a bigger one (and whatever is
drawn for it lands in the middle of the bigger one too). Here every screen is
moved to a slot of its own on that canvas, far enough from the next that the
moving light never crosses over, and gets the whole scene: the sky, 光
written in stroke order, the prompt, the shadow of a wrong passphrase and the
flood of light, each at the size drawn for it. Plymouth re-centres every
screen now and then on its own (once when the splash is shown, again when a
screen is plugged in, and it does not always say so), so every frame checks
the layout and puts any screen that has drifted back in its slot.
"""

import os

WORDS = ("greet", "hint", "checkjp", "checken", "wrongjp", "wrongen")
SINGLES = ("line", "cursor", "furigana", "caps", "bloom", "glow", "shadow", "flood") + WORDS
KEYS = ("W", "H", "cell", "u", "kx", "ky", "furi_y", "step", "marks_top", "line_y",
        "hints_top", "hint_gap", "shadow_w", "flood_w", "glow_w", "glow_h")
SLOT = 12000   # canvas pixels between screens: wider than any screen plus the light that moves off it
HEADS = 8

TEMPLATE = r"""# Hikari 99 boot screen. Generated by
# ~/.config/omarchy/lock-designs/hikari-99/boot/render.py from the Omarchy
# theme and wallpaper in use; edit that, not this.
#
# The sky is the Hikari 99 lock screen's, pre-drawn: the art's pixel grid,
# 12-bit color, a noise dither in eight frames shown four a second, so the
# cells sparkle the way the shader re-rolls them. 光 is written stroke by
# stroke. At the prompt: ひかり, pencil marks on a line of light, a breathing
# cursor, おかえりなさい. On submit 光 lights up while the disk checks; the
# prompt coming back means a wrong passphrase, and a cloud's shadow passes
# over. The root filesystem mounting means it opened: the clouds part along
# the slant in a flood of light. (If that signal never comes, five quiet
# seconds after a submit count as opened.)
#
# Every screen gets all of it, at its own size. Plymouth puts all screens on
# one canvas, centred on the largest: a smaller screen shows the middle of a
# bigger one, and what is drawn for it lands in the middle of the bigger one.
# So each screen is moved to a slot of its own (Window.SetX), @SLOT@ canvas
# pixels apart, wider than any screen plus the light that moves off it.
# Plymouth re-centres the screens on its own now and then (once right after
# the splash is shown, again on a hotplug, not always saying so), so every
# frame checks the layout and puts a drifted screen back (keep_layout).
#
# Everything loads up front: switch_root wipes the initramfs right after the
# unlock. A bare assignment inside a function makes a local, so state shared
# between callbacks lives in global.* or in arrays made at the top level.

Window.SetBackgroundTopColor(@NIGHT@);
Window.SetBackgroundBottomColor(@NIGHT@);

mode = Plymouth.GetMode();
global.boot_like = 1;
if (mode == "reboot" || mode == "shutdown") global.boot_like = 0;

# The drawings, one set per size: layout numbers, then the images
@SET_DATA@

loaded.n = 0;
sky.n = 0;
ks.n = 0;
mimg.n = 0;
@CONTAINERS@

@LOAD_SET@

# When each stroke of 光 starts, and for how long, in 50 Hz ticks
@SCHEDULE@
kseg.n = 0;
for (i = 0; i < @NSTROKES@; i++) {
  kseg[i] = -1;
  # On the way down 光 is simply there
  if (global.boot_like == 0) kseg[i] = @LASTSEG@;
}

# Per screen, and the sprites on it
hready.n = 0;
for (h = 0; h < @HEADS@; h++) hready[h] = 0;
hst.n = 0; hsc.n = 0; hox.n = 0; hoy.n = 0; hx.n = 0; hw.n = 0; hh.n = 0; hlinex.n = 0;
hsky.n = 0; hks.n = 0; hm.n = 0;
@HEAD_CONTAINERS@
skyS.n = 0; glowS.n = 0; shadowS.n = 0; bloomS.n = 0; kanS.n = 0; furiS.n = 0;
lineS.n = 0; cursorS.n = 0; mkS.n = 0; jpS.n = 0; enS.n = 0; capsS.n = 0;
floodL.n = 0; floodR.n = 0; lightS.n = 0; msgS.n = 0;

# The pencil marks: when each was made, and which of the four hands drew it
mkborn.n = 0;
mkvar.n = 0;
for (j = 0; j < 24; j++) {
  mkborn[j] = -100;
  mkvar[j] = j - Math.Int(j / 4) * 4;
}

global.tick = 0;
global.prompt = 0;
global.count = 0;
global.checking = -1;
global.flood = -1;
global.fail = -1;
global.chrome = 0;
global.opened = 0;
global.words = 0;
global.furi = 0;

fun sc(im, s) {
  if (s > 0.999 && s < 1.001) return im;
  return im.Scale(im.GetWidth() * s, im.GetHeight() * s);
}
fun X(h, v) { return hox[h] + v * hsc[h]; }
fun Y(h, v) { return hoy[h] + v * hsc[h]; }
fun snap(h, v) {
  c = L_cell[hst[h]];
  return Math.Int(v / c) * c;
}

# Each screen to its own slot on the canvas
fun arrange() {
  for (i = 0; i < @HEADS@; i++) {
    if (Window.GetWidth(i) > 0) {
      Window.SetX(i, i * @SLOT@);
      Window.SetY(i, 0);
    }
  }
}

fun set_words_head(h) {
  st = hst[h];
  if (global.words == 1) { a = H_checkjp[h]; b = H_checken[h]; }
  else if (global.words == 2) { a = H_wrongjp[h]; b = H_wrongen[h]; }
  else { a = H_greet[h]; b = H_hint[h]; }
  jpS[h].SetImage(a);
  jpS[h].SetPosition(X(h, L_W[st] / 2) - a.GetWidth() / 2, Y(h, L_hints_top[st]), 7);
  enS[h].SetImage(b);
  enS[h].SetPosition(X(h, L_W[st] / 2) - b.GetWidth() / 2, Y(h, L_hints_top[st]) + a.GetHeight() + L_hint_gap[st] * hsc[h], 7);
}

fun set_words(kind) {
  global.words = kind;
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) set_words_head(h);
  }
}

fun place_marks_head(h) {
  st = hst[h];
  n = global.count;
  step = L_step[st];
  x0 = snap(h, (L_W[st] - n * step) / 2);
  for (j = 0; j < 24; j++) {
    if (j < n) {
      mkS[h * 24 + j].SetPosition(X(h, x0 + j * step), Y(h, L_marks_top[st]), 7);
      mkS[h * 24 + j].SetOpacity(global.chrome);
    } else {
      mkS[h * 24 + j].SetOpacity(0);
    }
  }
  if (n == 0) cx = snap(h, L_W[st] / 2);
  else cx = x0 + n * step + snap(h, step / 2);
  cursorS[h].SetPosition(X(h, cx), Y(h, L_marks_top[st]) + (step * hsc[h] - H_cursor[h].GetHeight()) / 2, 7);
}

fun place_marks() {
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) place_marks_head(h);
  }
}

fun chrome_opacity(o) {
  global.chrome = o;
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) {
      lineS[h].SetOpacity(o);
      jpS[h].SetOpacity(o);
      enS[h].SetOpacity(o);
      for (j = 0; j < 24; j++) {
        if (j < global.count) mkS[h * 24 + j].SetOpacity(o);
        else mkS[h * 24 + j].SetOpacity(0);
      }
    }
  }
}

# The drawing set nearest a screen's size (the one drawn for it, when the
# screens at boot are the ones the theme was made on)
fun nearest_set(w, ht) {
  best = 0;
  bestd = -1;
  for (i = 0; i < @NSETS@; i++) {
    d = Math.Abs(L_W[i] - w) + Math.Abs(L_H[i] - ht);
    if (bestd < 0 || d < bestd) {
      best = i;
      bestd = d;
    }
  }
  return best;
}

# One screen, set up in its slot at the size drawn for it
fun setup_head(h) {
  w = Window.GetWidth(h);
  ht = Window.GetHeight(h);
  st = nearest_set(w, ht);
  load_set(st);
  s = w / L_W[st];
  if (ht / L_H[st] > s) s = ht / L_H[st];
  hst[h] = st;
  hsc[h] = s;
  hw[h] = w;
  hh[h] = ht;
  hx[h] = h * @SLOT@;
  hox[h] = hx[h] + (w - L_W[st] * s) / 2;
  hoy[h] = (ht - L_H[st] * s) / 2;

  frames = 1;
  if (global.boot_like == 1) frames = @FRAMES@;
  for (f = 0; f < frames; f++) hsky[h * @FRAMES@ + f] = sc(sky[st * @FRAMES@ + f], s);
  for (k = 0; k < @NK@; k++) hks[h * @NK@ + k] = sc(ks[st * @NK@ + k], s);
  for (k = 0; k < 8; k++) hm[h * 8 + k] = sc(mimg[st * 8 + k], s);
@SCALE_SINGLES@
  H_light[h] = I_light[st].Scale(w, ht);

  skyS[h] = Sprite(hsky[h * @FRAMES@]);
  skyS[h].SetPosition(hox[h], hoy[h], 0);

  glowS[h] = Sprite(H_glow[h]);
  glowS[h].SetPosition(X(h, 0), Y(h, L_H[st] - L_glow_h[st]), 1);
  glowS[h].SetOpacity(0.7);

  shadowS[h] = Sprite(H_shadow[h]);
  shadowS[h].SetPosition(X(h, 0 - L_shadow_w[st]), Y(h, 0), 2);
  shadowS[h].SetOpacity(0);

  bloomS[h] = Sprite(H_bloom[h]);
  bloomS[h].SetPosition(X(h, L_kx[st]), Y(h, L_ky[st]), 4);
  bloomS[h].SetOpacity(0);

  for (i = 0; i < @NSTROKES@; i++) {
    kanS[h * @NSTROKES@ + i] = Sprite();
    kanS[h * @NSTROKES@ + i].SetPosition(X(h, L_kx[st]), Y(h, L_ky[st]), 5);
    if (kseg[i] >= 0) kanS[h * @NSTROKES@ + i].SetImage(hks[h * @NK@ + i * @SEGMENTS@ + kseg[i]]);
  }

  furiS[h] = Sprite(H_furigana[h]);
  furiS[h].SetPosition(X(h, L_W[st] / 2) - H_furigana[h].GetWidth() / 2, Y(h, L_furi_y[st]), 6);
  furiS[h].SetOpacity(global.furi);

  lineS[h] = Sprite(H_line[h]);
  hlinex[h] = snap(h, (L_W[st] - H_line[h].GetWidth() / s) / 2);
  lineS[h].SetPosition(X(h, hlinex[h]), Y(h, L_line_y[st]), 6);
  lineS[h].SetOpacity(global.chrome);

  cursorS[h] = Sprite(H_cursor[h]);
  cursorS[h].SetOpacity(0);

  for (j = 0; j < 24; j++) {
    mkS[h * 24 + j] = Sprite();
    mkS[h * 24 + j].SetOpacity(0);
    if (j < global.count) mkS[h * 24 + j].SetImage(hm[h * 8 + mkvar[j] * 2 + 1]);
  }

  jpS[h] = Sprite();
  enS[h] = Sprite();
  jpS[h].SetOpacity(global.chrome);
  enS[h].SetOpacity(global.chrome);

  capsS[h] = Sprite(H_caps[h]);
  capsS[h].SetPosition(X(h, hlinex[h]) + H_line[h].GetWidth() + 12 * s, Y(h, L_marks_top[st]) + (L_step[st] * s - H_caps[h].GetHeight()) / 2, 7);
  capsS[h].SetOpacity(0);

  floodL[h] = Sprite(H_flood[h]);
  floodL[h].SetOpacity(0);
  floodR[h] = Sprite(H_flood[h]);
  floodR[h].SetOpacity(0);

  lightS[h] = Sprite(H_light[h]);
  lightS[h].SetPosition(hx[h], 0, 9);
  lightS[h].SetOpacity(0);

  msgS[h] = Sprite();
  msgS[h].SetOpacity(0);

  hready[h] = 1;
  set_words_head(h);
  place_marks_head(h);
}

arrange();
for (h = 0; h < @HEADS@; h++) {
  if (Window.GetWidth(h) > 0) setup_head(h);
}

# Every screen in its slot, every screen set up. Plymouth moves them back to
# the centre on its own now and then, so this runs every frame: a moved
# screen goes straight back, a new one gets its scene.
fun keep_layout() {
  for (i = 0; i < @HEADS@; i++) {
    if (Window.GetWidth(i) > 0) {
      if (Window.GetX(i) != i * @SLOT@ || Window.GetY(i) != 0) {
        Window.SetX(i, i * @SLOT@);
        Window.SetY(i, 0);
      }
      if (hready[i] != 1) setup_head(i);
    }
  }
}

fun hotplug_callback() {
  keep_layout();
}

fun stop_flood() {
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) {
      floodL[h].SetOpacity(0);
      floodR[h].SetOpacity(0);
      lightS[h].SetOpacity(0);
    }
  }
}

fun bloom_opacity(o) {
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) bloomS[h].SetOpacity(o);
  }
}

fun furi_opacity(o) {
  global.furi = o;
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) furiS[h].SetOpacity(o);
  }
}

fun open_up() {
  if (global.opened == 1 || global.boot_like == 0) return;
  global.opened = 1;
  global.checking = -1;
  global.flood = global.tick;
}

# The root filesystem is mounted: the disk opened
fun root_mounted_callback() {
  open_up();
}

fun display_password_callback(prompt_text, count) {
  if (global.checking >= 0 || global.flood >= 0) {
    # The prompt again after a submit: that passphrase was wrong
    global.checking = -1;
    global.flood = -1;
    global.fail = global.tick;
    stop_flood();
    bloom_opacity(0);
    set_words(2);
  } else if (global.fail < 0) {
    set_words(0);
  }
  global.prompt = 1;
  if (count > 24) count = 24;
  if (count > global.count) {
    for (j = global.count; j < count; j++) {
      mkborn[j] = global.tick;
      for (h = 0; h < @HEADS@; h++) {
        if (hready[h] == 1) mkS[h * 24 + j].SetImage(hm[h * 8 + mkvar[j] * 2]);
      }
    }
  }
  global.count = count;
  chrome_opacity(1);
  place_marks();
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) cursorS[h].SetOpacity(0.6);
  }
}

fun display_normal_callback() {
  if (global.prompt == 1) {
    global.prompt = 0;
    for (h = 0; h < @HEADS@; h++) {
      if (hready[h] == 1) {
        cursorS[h].SetOpacity(0);
        capsS[h].SetOpacity(0);
      }
    }
    if (global.boot_like == 1) {
      global.checking = global.tick;
      set_words(1);
    } else {
      chrome_opacity(0);
    }
  }
}

fun refresh_callback() {
  keep_layout();
  global.tick = global.tick + 1;
  t = global.tick;
  breath = 0.5 - 0.5 * Math.Cos(2 * Math.Pi * t / 600);

  # The sky's cells re-roll and the lilac corner breathes, four times a second
  if (global.boot_like == 1 && t - Math.Int(t / 12) * 12 == 0) {
    f = Math.Int(t / 12);
    f = f - Math.Int(f / @FRAMES@) * @FRAMES@;
    for (h = 0; h < @HEADS@; h++) {
      if (hready[h] == 1) {
        skyS[h].SetImage(hsky[h * @FRAMES@ + f]);
        glowS[h].SetOpacity(0.45 + 0.55 * breath);
      }
    }
  }

  # 光, written in stroke order
  if (global.boot_like == 1 && t <= @WRITE_END@ + 2) {
    for (i = 0; i < @NSTROKES@; i++) {
      u = (t - wstart[i]) / wdur[i];
      if (u > 0) {
        j = Math.Int(u * @SEGMENTS@);
        if (j > @LASTSEG@) j = @LASTSEG@;
        if (kseg[i] != j) {
          kseg[i] = j;
          for (h = 0; h < @HEADS@; h++) {
            if (hready[h] == 1) kanS[h * @NSTROKES@ + i].SetImage(hks[h * @NK@ + i * @SEGMENTS@ + j]);
          }
        }
      }
    }
  }
  if (global.boot_like == 1 && t > @WRITE_END@ && t < @WRITE_END@ + 60) furi_opacity((t - @WRITE_END@) / 60);
  if (global.boot_like == 0 && t < 60) furi_opacity(t / 60);

  # A new pencil mark: half drawn, then whole
  for (j = 0; j < global.count; j++) {
    if (t - mkborn[j] == 4) {
      for (h = 0; h < @HEADS@; h++) {
        if (hready[h] == 1) mkS[h * 24 + j].SetImage(hm[h * 8 + mkvar[j] * 2 + 1]);
      }
    }
  }

  if (global.prompt == 1 && t - Math.Int(t / 5) * 5 == 0) {
    caps = Plymouth.GetCapslockState();
    for (h = 0; h < @HEADS@; h++) {
      if (hready[h] == 1) {
        cursorS[h].SetOpacity(0.35 + 0.45 * breath);
        if (caps) capsS[h].SetOpacity(1);
        else capsS[h].SetOpacity(0);
      }
    }
  }

  # Checking: 光 lights up until the root filesystem mounts (it opened) or
  # the prompt comes back (it did not). Five quiet seconds count as opened.
  if (global.checking >= 0) {
    a = (t - global.checking) / 60;
    if (a > 1) a = 1;
    bloom_opacity(a * 0.7);
    if (t - global.checking >= 250) open_up();
  }

  # The unlock: the clouds part along the slant and the light floods in
  if (global.flood >= 0) {
    p = (t - global.flood) / 80;
    if (p >= 1) {
      stop_flood();
      bloom_opacity(0.35);
      global.flood = -1;
    } else if (t - Math.Int(t / 2) * 2 == 0) {
      if (p < 0.35) lo = p / 0.35 * 0.55;
      else lo = (1 - p) / 0.65 * 0.55;
      o = 1 - p * 3;
      if (o < 0) o = 0;
      for (h = 0; h < @HEADS@; h++) {
        if (hready[h] == 1) {
          st = hst[h];
          cx = L_W[st] / 2 - L_flood_w[st] / 2;
          d = p * L_W[st] * 0.75;
          floodL[h].SetPosition(X(h, cx - d), Y(h, 0), 8);
          floodR[h].SetPosition(X(h, cx + d), Y(h, 0), 8);
          floodL[h].SetOpacity(1 - p);
          floodR[h].SetOpacity(1 - p);
          lightS[h].SetOpacity(lo);
          bloomS[h].SetOpacity(0.7 + 0.3 * Math.Sin(Math.Pi * p));
        }
      }
      chrome_opacity(o);
      furi_opacity(o);
    }
  }

  # A wrong passphrase: a cloud's shadow crosses, the marks are rubbed out
  if (global.fail >= 0) {
    p = (t - global.fail) / 75;
    if (p >= 1) {
      for (h = 0; h < @HEADS@; h++) {
        if (hready[h] == 1) shadowS[h].SetOpacity(0);
      }
      global.fail = -1;
    } else if (t - Math.Int(t / 2) * 2 == 0) {
      for (h = 0; h < @HEADS@; h++) {
        if (hready[h] == 1) {
          st = hst[h];
          shadowS[h].SetPosition(X(h, 0 - L_shadow_w[st] + (L_W[st] + L_shadow_w[st]) * p), Y(h, 0), 2);
          shadowS[h].SetOpacity(1);
          if (global.count > 0 && p < 0.3) {
            for (j = 0; j < global.count; j++) mkS[h * 24 + j].SetOpacity(1 - p / 0.3);
          }
        }
      }
    }
  }
}

fun display_message_callback(text) {
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) {
      msgS[h].SetImage(Image.Text(text, @INK@, 0.8, "Sans 12"));
      msgS[h].SetPosition(hx[h] + 24, hh[h] - 48, 10);
      msgS[h].SetOpacity(1);
    }
  }
}

fun hide_message_callback(text) {
  for (h = 0; h < @HEADS@; h++) {
    if (hready[h] == 1) msgS[h].SetOpacity(0);
  }
}

Plymouth.SetDisplayPasswordFunction(display_password_callback);
Plymouth.SetDisplayNormalFunction(display_normal_callback);
Plymouth.SetRefreshFunction(refresh_callback);
Plymouth.SetRootMountedFunction(root_mounted_callback);
Plymouth.SetDisplayMessageFunction(display_message_callback);
Plymouth.SetHideMessageFunction(hide_message_callback);
Plymouth.SetDisplayHotplugFunction(hotplug_callback);
"""


def write_script(out, layout, strokes, segments, frames, schedule, night, ink):
    """Write omarchy-boot.script into `out` for the drawing sets in `layout`."""
    sets = sorted(layout, key=lambda t: (layout[t]["W"] * layout[t]["H"], t))
    nk = len(strokes) * segments
    floats = lambda c: ", ".join("%.3f" % (v / 255) for v in c)

    set_data = []
    for si, tag in enumerate(sets):
        set_data.append(f"# set {si}: drawn for {layout[tag]['W']} x {layout[tag]['H']}")
        set_data.append(" ".join(f"L_{k}[{si}] = {layout[tag][k]};" for k in KEYS))
    set_data = [" ".join(f"L_{k}.n = 0;" for k in KEYS)] + set_data
    containers = " ".join(f"I_{n}.n = 0;" for n in SINGLES + ("light",))

    load = ["fun load_set(st) {", "  if (loaded[st] == 1) return;", "  loaded[st] = 1;"]
    for si, tag in enumerate(sets):
        load.append(f"  if (st == {si}) {{")
        load.append(f'    sky[{si * frames}] = Image("h99-{tag}-sky-0.png");')
        load.append("    if (global.boot_like == 1) {")
        for f in range(1, frames):
            load.append(f'      sky[{si * frames + f}] = Image("h99-{tag}-sky-{f}.png");')
        load.append("    }")
        for i in range(len(strokes)):
            for j in range(segments):
                load.append(f'    ks[{si * nk + i * segments + j}] = Image("h99-{tag}-k{i}-{j}.png");')
        for v in range(4):
            for f in range(2):
                load.append(f'    mimg[{si * 8 + v * 2 + f}] = Image("h99-{tag}-mark{v}-{f}.png");')
        for name in SINGLES + ("light",):
            load.append(f'    I_{name}[{si}] = Image("h99-{tag}-{name}.png");')
        load.append("  }")
    load.append("}")

    schedule_lines = "\n".join(f"wstart[{i}] = {a}; wdur[{i}] = {d};" for i, (a, d) in enumerate(schedule))
    head_containers = " ".join(f"H_{n}.n = 0;" for n in SINGLES + ("light",))
    scale_singles = "\n".join(f"  H_{n}[h] = sc(I_{n}[st], s);" for n in SINGLES)
    write_end = schedule[-1][0] + schedule[-1][1]

    script = (TEMPLATE
              .replace("@SET_DATA@", "\n".join(set_data))
              .replace("@CONTAINERS@", containers)
              .replace("@LOAD_SET@", "\n".join(load))
              .replace("@SCHEDULE@", "wstart.n = 0; wdur.n = 0;\n" + schedule_lines)
              .replace("@HEAD_CONTAINERS@", head_containers)
              .replace("@SCALE_SINGLES@", scale_singles)
              .replace("@NIGHT@", floats(night))
              .replace("@INK@", floats(ink))
              .replace("@FRAMES@", str(frames))
              .replace("@NK@", str(nk))
              .replace("@NSTROKES@", str(len(strokes)))
              .replace("@SEGMENTS@", str(segments))
              .replace("@LASTSEG@", str(segments - 1))
              .replace("@WRITE_END@", str(write_end))
              .replace("@NSETS@", str(len(sets)))
              .replace("@HEADS@", str(HEADS))
              .replace("@SLOT@", str(SLOT)))
    assert "@" not in script, "unfilled placeholder"
    with open(os.path.join(out, "omarchy-boot.script"), "w") as f:
        f.write(script)
